- name: "System basic enviroment setup!"
  #  gather_facts: false
  hosts: desktop
  remote_user: "oliver"
  roles:
    # - base
    # - pip
    # - gitconfig
    # - golang
    # - sshd
    # - timezone
    # - chrony
    # - fcitx
    # - nodejs
    # - profile
    # - i3wm-desktop
    # - alacritty
    - meow
    #- powerline-fonts
    #- spacevim
