- name: "Server Init!"
  # gather_facts: false
  hosts: vultr
  remote_user: "root"
  roles:
    #    - role: oefenweb.swapfile
    #      swapfile_size: 4GB
    - base
    - golang
    - timezone
    - chrony
    - sshd
    - role: ss-go-server
