- name: "Server Init!"
  # gather_facts: false
  hosts: vultr
  remote_user: "root"
  roles:
    - role: ss-libev
      PortMaxNum: 20
      SSPassword: linux10000
    
    # - role: geerlingguy.swap
    #   swap_file_size_mb: '4096'
    # - base
      #    - golang
    # - timezone
    # - chrony
    # - sshd
    #    - role: ss-go-server
      #      port_nums: 20
      #      ss_password: linux10000
      #      encrypt_method: aes-256-cfb
      #      timeout: 600
