#- name: Install fish
#  become: yes
#  package:
#    state: latest
#    name: fish

- name: Create user "{{ USER }}"
  user:
    name: "{{ item }}"
    shell: /bin/bash
  with_items:
    - "{{ users }}"


- name: "Set authorized key taken from file"
  authorized_key:
    user: "{{ USER }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

