#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # default_indent = 8
    # chinese layer
    vim_help_language = "cn"
    lint_on_the_fly = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "VersionControl"

[[layers]]
name = "denite"

[[layers]]
name = "chinese"

[[layers]]
name = "cscope"

[[layers]]
name = "gtags"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#scheme"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#python"
format_on_save = 1
python_file_head = [
  '# -*- coding: utf-8 -*-',
  '',
  ''
]

[[layers]]
name = "lsp"
filetypes = [
  "rust",
  "go",
  "python",
  "c"
]
[layers.override_cmd]
go = ['gopls', '-mode', 'stdio']


[[custom_plugins]]
name = "editorconfig/editorconfig-vim"
