- name: "Download Spacevim install shell script."
  get_url:
    url: "{{ spacevim_script_url }}"
    dest: "{{ spacevim_script_path }}"
    mode: u+rwx

- name: "Execute Spacevim install script"
  async: 45
  poll: 5
  shell: "{{ spacevim_script_path }} --install neovim"
  register: spacevim_install_result

- debug:
    var: spacevim_install_result.stdout_lines
