- name: Include OS-specific variables.
  include_vars: '{{ ansible_distribution }}.yaml'

- name: "Setting repositories mirro"
  shell: "pacman-mirrors -c China -m rank"
  
- name: "Upgrade whole System"
  pacman: 
    upgrade: yes
    
- name: "Install package {{ packages }}."
  pacman:
    state: latest 
    name: "{{ packages }}"
    update_cache: yes

