- name: Include OS-specific variables.
  include_vars: '{{ ansible_distribution }}.yaml'

- name: "Base package setup"
  include_tasks: "{{ ansible_distribution }}.yaml"

- name: "Install package {{ packages }}."
  become: yes
  package:
    state: latest
    name: "{{ packages }}"
