- name: "Update all packages to the latest version"
  apt:
    upgrade: dist


- name: "Ubuntu ppa support"
  apt:
    name: "software-properties-common"
    state: latest


# Add specified repository into sources list.
- name: "Add goalng ppa"
  apt_repository:
    repo: ppa:longsleep/golang-backports
    
    
- name: "Install Ubuntu package {{ ubuntu_packages }}"
  apt:
    name: "{{ ubuntu_packages }}"
    state: latest
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  apt:
    autoremove: yes
