- name: install package alacritty
  become: yes
  package:
    state: latest
    name: alacritty

- name: create alacritty config directory
  file:
    state: directory
    path: $HOME/.config/alacritty

- name: init alacritty config file
  copy:
    src: alacritty.yml
    dest: $HOME/.config/alacritty

