- name: Download frp server
  get_url:
    url: https://github.com/fatedier/frp/releases/download/v0.31.0/frp_0.31.0_linux_amd64.tar.gz
    dest: $HOME/frp_0.31.0_linux_amd64.tar.gz

- name: Will create $HOME/frp directory
  become: yes
  file:
    state: directory
    path: $HOME/frp

- name: uncompress frp archive
  unarchive:
    src: $HOME/frp_0.31.0_linux_amd64.tar.gz
    remote_src: yes
    dest: $HOME/frp

- name: create frp server binary link to /usr/bin/
  file:
    src: $HOME/frp/frps
    dest: /usr/bin/frps
    state: link

- name: Will create /etc/frp directory
  become: yes
  file:
    state: directory
    path: /etc/frp

- name: copy frps.ini to /etc/frp/frps.ini
  copy:
    src: $HOME/frp/fprs.ini
    remote_src: yes
    dest: /etc/frp/frps.ini

- name: copy frps.server to /etc/systemd/system/frps.service
  copy:
    src: $HOME/frp/systemd/frps.service
    remote_src: yes
    dest: /etc/systemd/system/frps.service

- name: Enable and start frps.service
  become: yes
  systemd:
    name: frps
    enabled: yes
    state: restarted
    daemon_reload: yes

