- name: "Will copy i3 config file to remote"
  copy:
    src: "i3/config"
    dest: "$HOME/.i3/"

- name: "Will copy dunst file to remote"
  copy:
    src: "config/dunst"
    dest: "$HOME/.config/dunst/"

- name: "Will copy xresources file to remote"
  copy:
    src: "Xresources"
    dest: "$HOME/.Xresources"

